title = "Atlas Secret Scanning Rules"

[extend]
useDefault = true

[[rules]]
id = "paddle-api-key"
description = "Paddle API Key"
regex = '''pdl_(live|test)_[0-9a-zA-Z]{20,}'''
tags = ["paddle", "apikey"]

[[rules]]
id = "supabase-key"
description = "Supabase Service Key"
regex = '''SUPABASE_SERVICE_KEY|SUPABASE_SERVICE_ROLE_KEY'''
tags = ["supabase", "apikey"]

[[rules]]
id = "slack-token"
description = "Slack Webhook or Token"
regex = '''xox[baprs]-[0-9a-zA-Z-]+'''
tags = ["slack", "token"]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|secret|token)\s*=\s*["']?[0-9a-zA-Z_-]{20,}["']?'''
tags = ["generic", "apikey"]

[[rules]]
id = "openai-key"
description = "OpenAI API Key"
regex = '''sk-(live|test)?-[0-9a-zA-Z]{20,}'''
tags = ["openai", "apikey"]

[[rules]]
id = "anthropic-key"
description = "Anthropic API Key"
regex = '''sk-ant-[0-9a-zA-Z-]+'''
tags = ["anthropic", "apikey"]

[[rules]]
id = "database-url"
description = "Database URL with credentials"
regex = '''postgresql://[^:]+:[^@]+@[^/]+'''
tags = ["database", "credentials"]

[allowlist]
description = "Allow safe patterns and files"
# Example safe env placeholders
regexes = [
  '''your_api_key_here''',
  '''example_key''',
  '''dummy_secret''',
  '''your_token_here''',
  '''your_webhook_secret_here''',
  '''your_supabase_url''',
  '''your_supabase_anon_key''',
  '''pri_core_plan''',
  '''pri_studio_plan''',
  '''your_client_token_here''',
  '''test-anon-key''',
  '''test\.supabase\.co''',
  '''VITE_SUPABASE_URL''',
  '''VITE_SUPABASE_ANON_KEY''',
  '''SUPABASE_URL''',
  '''SUPABASE_ANON_KEY''',
  '''SUPABASE_SERVICE_KEY''',
  '''SUPABASE_SERVICE_ROLE_KEY''',
  '''process\.env\.SUPABASE''',
  '''Deno\.env\.get\("SUPABASE''',
  '''import\.meta\.env\.VITE_SUPABASE''',
]
paths = [
  '''supabase\.env\.example''',
  '''README\.md''',
  '''README\.LAUNCH\.md''',
  '''docs/.*''',
  '''\.env\.example''',
  '''\.env\.local\.example''',
  '''\.env\.production\.example''',
  '''\.env\.test\.example''',
  '''\.env\.staging\.example''',
  '''\.env\.backup.*''',
  '''\.gitleaks\.toml''',
  '''scripts/.*''',
  '''supabase/\.temp/.*''',
  '''supabase/supabase-temp-backup/.*''',
  '''test-.*\.sh''',
  '''tier-gate-setup\.sh''',
  '''vitest\.config\.ts''',
  '''src/vite-env\.d\.ts''',
  '''src/lib/supabaseClient\.ts''',
  '''src/utils/authFetch\.ts''',
  '''\.github/workflows/.*''',
  '''backend/.*''',
  '''config/.*''',
  '''deploy.*\.sh''',
  '''atlas-migration.*''',
  '''monitor-.*\.sh''',
  '''sanity-.*\.sh''',
  '''setup-.*\.sh''',
  '''deploy-config\.js''',
  '''public/\.env''',
  '''\.md$''',
  '''\.pem$''',
  '''test-.*\.js''',
  '''src/__tests__/.*''',
  '''src/components/.*''',
  '''src/lib/.*''',
  '''supabase/functions/.*''',
]
