title = "Atlas Secret Scan Rules"

# --- Paddle ---
[[rules]]
id = "paddle-api-key"
description = "Paddle API Key"
regex = '''paddle_(live|test)_[0-9a-zA-Z]{32}'''
tags = ["paddle", "api", "key"]

# --- Supabase ---
[[rules]]
id = "supabase-service-role-key"
description = "Supabase Service Role Key"
regex = '''eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.[0-9a-zA-Z\-_]+.[0-9a-zA-Z\-_]+'''
tags = ["supabase", "service", "jwt"]

# --- Slack ---
[[rules]]
id = "slack-webhook"
description = "Slack Incoming Webhook"
regex = '''https://hooks.slack.com/services/T[0-9A-Z]{8}/B[0-9A-Z]{8,12}/[a-zA-Z0-9]{24}'''
tags = ["slack", "webhook"]

# --- CI/CD ---
[[rules]]
id = "cicd-alert-token"
description = "CI/CD Alert Token"
regex = '''(CICD_ALERT_TOKEN|ALERT_TOKEN)\s*=\s*[A-Za-z0-9_\-]{24,40}'''
tags = ["cicd", "token"]

# --- MailerLite ---
[[rules]]
id = "mailerLite-api-key"
description = "MailerLite API Key"
regex = '''[0-9a-f]{32}'''
tags = ["mailerlite", "api", "key"]

# --- MailerSend ---
[[rules]]
id = "mailerSend-api-token"
description = "MailerSend API Token"
regex = '''mlsn_[0-9a-zA-Z\-_]{20,}'''
tags = ["mailersend", "api", "token"]

# --- OpenAI ---
[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{32,}'''
tags = ["openai", "api", "key"]

# --- Anthropic ---
[[rules]]
id = "anthropic-api-key"
description = "Anthropic API Key"
regex = '''sk-ant-[0-9a-zA-Z]{32,}'''
tags = ["anthropic", "api", "key"]

# --- Railway ---
[[rules]]
id = "railway-token"
description = "Railway Project Token"
regex = '''rail_[a-zA-Z0-9\-_]{32,}'''
tags = ["railway", "api", "token"]

# --- Vercel ---
[[rules]]
id = "vercel-api-key"
description = "Vercel API Token"
regex = '''vercel\.[a-zA-Z0-9\-_]{30,}'''
tags = ["vercel", "api", "token"]

# --- GitHub PAT ---
[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''gh[pousr]_[A-Za-z0-9_]{36}'''
tags = ["github", "pat", "token"]

# --- Allowlist (ignore safe files/placeholders) ---
[allowlist]
description = "Allow gitleaks config itself and safe placeholders"
files = [
  ".gitleaks.toml",
  ".env.example",
  "supabase.env.example",
  "README.md",
  "docs/*",
  ".cursorrules",
  "supabase/functions/**/*",
  "scripts/setup-git-secrets.sh",
  "scripts/pre-commit-security-scan.sh",
  "scripts/*security*.sh"
]
regexes = [
  "your_api_key_here",
  "example_key",
  "placeholder",
  "your-service-role-key",
  "your_token_here",
  "your_webhook_secret_here",
  "your_supabase_url",
  "your_supabase_anon_key",
  "your_cicd_alert_token_here",
  # Security script patterns (these are detection regex, not actual secrets)
  "sk-ant-\\[a-zA-Z0-9\\\\\\-\\]\\{95,\\}",
  "AKIA\\[0-9A-Z\\]\\{16\\}",
  "eyJ\\[a-zA-Z0-9_-\\]\\{50,\\}\\.[a-zA-Z0-9_-\\]\\{50,\\}\\.[a-zA-Z0-9_-\\]\\{50,\\}"
]