#!/bin/bash
echo "🔍 Railway API Key Diagnostic"
echo "=============================="
echo ""
echo "Check Railway logs for these messages after redeploy:"
echo ""
echo "✅ GOOD SIGNS:"
echo "  - '✅ Set (sk-ant-...)'"
echo "  - 'ANTHROPIC_API_KEY_LENGTH: 120' (or similar)"
echo ""
echo "❌ BAD SIGNS:"
echo "  - '⚠️ ANTHROPIC_API_KEY format invalid'"
echo "  - 'ANTHROPIC_API_KEY_LENGTH: 0'"
echo "  - 'invalid x-api-key' (401 error)"
echo ""
echo "📋 To fix:"
echo "1. Railway → Variables → ANTHROPIC_API_KEY"
echo "2. Click to edit"
echo "3. Copy fresh key from: https://console.anthropic.com/settings/keys"
echo "4. Paste (NO spaces before/after)"
echo "5. Save → Railway auto-redeploys"
echo ""
echo "🔗 Railway Logs:"
echo "https://railway.app/project/atlas-production-2123/logs"
