-- Create logs table for error + event tracking
create table if not exists logs (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('info', 'warn', 'error')),
  message text not null,
  stack text,
  context jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- RLS: allow only service role inserts (not from client apps)
alter table logs enable row level security;
create policy "Allow inserts with service role"
  on logs for insert
  using (auth.role() = 'service_role');
