name: Atlas AI Nightly E2E Validation

on:
  schedule:
    # Run nightly at 2 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  nightly-e2e:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests (Nightly UX Validation)
        id: e2e
        run: |
          npx playwright test --reporter=list > playwright-report.txt || true

      # Create a GitHub Issue if the nightly E2E failed
      - name: Create GitHub Issue on Failure
        id: create_issue
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "⚠️ Nightly Playwright E2E Tests Failed"
          content-filepath: playwright-report.txt
          labels: bug, e2e, nightly

      # ✉️ Email the failure report to admin@otiumcreations.com
      - name: Email Nightly E2E Failure Alert
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "⚠️ Nightly Playwright E2E Failed — ${{ github.repository }}"
          to: "admin@otiumcreations.com"
          from: ${{ secrets.SMTP_FROM }}
          content_type: text/html
          body: |
            <p>Nightly Playwright E2E tests failed for <strong>${{ github.repository }}</strong>.</p>
            <p>Ref: <code>${{ github.ref }}</code></p>
            <p>Auto-created issue: <a href="${{ steps.create_issue.outputs.issue_url }}">${{ steps.create_issue.outputs.issue_url }}</a></p>
            <p>The raw test output is attached.</p>
          attachments: |
            playwright-report.txt

      # If the nightly E2E passed, close any open failure issues automatically
      - name: Find Previous Failure Issues
        id: find_issue
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: "bug,e2e,nightly",
              state: "open"
            });
            if (issues.data.length > 0) {
              core.setOutput("issue_number", issues.data[0].number);
            }

      - name: Close Previous Failure Issue (if any)
        if: success() && steps.find_issue.outputs.issue_number
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ steps.find_issue.outputs.issue_number }}
          comment: "✅ Nightly Playwright E2E tests passed — closing this issue automatically."
