name: Secret Scan

on:
  pull_request:
  push:
    branches: [main, develop]
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks Secret Scan
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2.3.0
        env:
          GITLEAKS_CONFIG: .gitleaks.toml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-path: .gitleaks.toml
          report-format: sarif
          sarif-file: results.sarif

      - name: Notify Slack/Discord on Failure
        if: failure()
        env:
          ALERT_PROXY_URL: ${{ secrets.ALERT_PROXY_URL }}
          ALERT_TOKEN: ${{ secrets.CICD_ALERT_TOKEN }}
        run: |
          curl -X POST -H "Content-type: application/json" \
               -H "Authorization: Bearer $ALERT_TOKEN" \
               --data "{
                 \"attachments\": [
                   {
                     \"color\": \"#FF0000\",
                     \"title\": \"🚨 Secret Scan FAILED\",
                     \"text\": \"Secret scan failed in *${{ github.repository }}* on *${{ github.ref_name }}*\\n\\nCheck workflow logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\",
                     \"footer\": \"GitHub Actions • Atlas Security • Alert Proxy\",
                     \"ts\": $(date +%s)
                   }
                 ]
               }" \
               $ALERT_PROXY_URL

      - name: Success Notification
        if: success()
        run: |
          echo "✅ Secret scan completed successfully - no secrets detected"
