name: Secret Scan & Security Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    name: Scan for secrets and security issues
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for better scanning
    
    - name: Run secret scanning
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified
    
    - name: Check for .env files
      run: |
        if find . -name ".env" -not -path "./.git/*" | grep -q .; then
          echo "❌ .env files found in repository!"
          find . -name ".env" -not -path "./.git/*"
          exit 1
        else
          echo "✅ No .env files found"
        fi
    
    - name: Check for common secret patterns
      run: |
        # Check for API keys, secrets, etc.
        if grep -r -i -E "(api[_-]?key|secret|password|token).*=.*[a-zA-Z0-9]{20,}" --exclude-dir=.git --exclude="*.md" .; then
          echo "❌ Potential secrets detected in code!"
          exit 1
        else
          echo "✅ No obvious secrets found"
        fi
    
    - name: Security audit
      run: |
        if [ -f package.json ]; then
          npm audit --audit-level=moderate
        fi

  code-quality:
    runs-on: ubuntu-latest
    name: Code quality checks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint || echo "⚠️ Linting not configured yet"
    
    - name: Run type checking
      run: npm run type-check || echo "⚠️ Type checking not configured yet"
    
    - name: Check for circular dependencies
      run: |
        npx madge --circular src/ || echo "⚠️ Circular dependency check not configured yet"
