name: Security Scan & Push Protection

on:
  push:
    branches: [ main, develop, refactor/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security & Secret Scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for secret scanning
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Detect secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified
    
    - name: Check for .env files
      run: |
        if find . -name ".env" -not -path "./.git/*" | grep -q .; then
          echo "❌ .env files detected in repository!"
          find . -name ".env" -not -path "./.git/*"
          exit 1
        else
          echo "✅ No .env files found"
        fi
    
    - name: Check for hardcoded secrets
      run: |
        # Check for common secret patterns (exclude .env, docs, venv, and package-lock files)
        if grep -r -i "sk-[a-zA-Z0-9]" --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.venv --exclude-dir=venv --exclude=".env" --exclude="*.md" --exclude="package-lock.json" .; then
          echo "❌ Potential OpenAI API keys detected!"
          exit 1
        fi
        
        if grep -r -i "pk_[a-zA-Z0-9]" --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.venv --exclude-dir=venv --exclude=".env" --exclude="*.md" --exclude="package-lock.json" .; then
          echo "❌ Potential Paddle API keys detected!"
          exit 1
        fi
        
        if grep -r -i "eyJ[a-zA-Z0-9]" --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.venv --exclude-dir=venv --exclude=".env" --exclude="*.md" --exclude="package-lock.json" .; then
          echo "❌ Potential JWT tokens detected!"
          exit 1
        fi
        
        echo "✅ No hardcoded secrets detected"
    
    - name: Dependency vulnerability scan
      run: |
        npm audit --audit-level=high
        if [ $? -ne 0 ]; then
          echo "❌ High or critical vulnerabilities found!"
          exit 1
        fi
        echo "✅ No high or critical vulnerabilities found"

  pre-commit-checks:
    runs-on: ubuntu-latest
    name: Pre-commit Validation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Type check
      run: npm run typecheck
    
    - name: Lint check
      run: npm run lint -- --max-warnings=1000
    
    - name: Test check
      run: npm run test
