name: CI Tests

on:
  push:
    branches:
      - main
      - refactor/**
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: TypeScript Check
        run: npm run typecheck

      - name: Unit Tests
        run: npm run test:unit

      - name: Integration Tests
        run: npm run test:int

      - name: E2E Tests (allowed to fail for now)
        run: npm run test:e2e || true
