name: Test CI/CD Alert
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  test-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Gather Git info
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Send alert to Supabase function
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/cicd-alert" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -d "{
              \"stage\": \"GitHub Workflow - Test CI/CD Alert\",
              \"status\": \"success\",
              \"details\": \"Triggered on branch: $BRANCH_NAME, Commit: $COMMIT_HASH\"
            }"

