name: Test CI/CD Alert

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send CI/CD Alert
        env:
          SUPABASE_FUNCTION_URL: ${{ secrets.SUPABASE_FUNCTION_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          curl -v -sS --fail \
            -X POST \
            "$SUPABASE_FUNCTION_URL/cicd-alert" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Content-Type: application/json" \
            -d '{"message": "CI/CD alert test triggered from GitHub Actions"}'
