name: Test Slack Failure Alert

on:
  workflow_dispatch:

jobs:
  slack-failure-test:
    runs-on: ubuntu-latest
    steps:
      - name: Send failure Slack alert via proxy
        env:
          ALERT_PROXY_URL: ${{ secrets.ALERT_PROXY_URL }}
          ALERT_TOKEN: ${{ secrets.CICD_ALERT_TOKEN }}
        run: |
          curl -X POST -H "Content-type: application/json" \
               -H "Authorization: Bearer $ALERT_TOKEN" \
               --data "{
                 \"attachments\": [
                   {
                     \"color\": \"#FF0000\",
                     \"title\": \"🚨 Atlas CICD Failure Test\",
                     \"text\": \"This is a FAILURE message test via Supabase Edge Function. Use this format for secret scan alerts.\",
                     \"footer\": \"GitHub Actions • Atlas Security • Alert Proxy\",
                     \"ts\": $(date +%s)
                   }
                 ]
               }" \
               $ALERT_PROXY_URL
