name: Test CI/CD Alert

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug Supabase Function URL
        run: |
          echo "🔍 Supabase Function URL (from secrets):"
          echo "${{ secrets.SUPABASE_FUNCTION_URL }}"

      - name: Send CI/CD Alert
        run: |
          curl -v -sS --fail \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"stage":"Debug Test","status":"success","details":"Verifying Supabase URL"}' \
            "${{ secrets.SUPABASE_FUNCTION_URL }}/cicd-alert"
