name: Test CI/CD Alert
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Send CI/CD Alert
        run: |
          curl -sS --fail \
            -X POST "${{ secrets.SUPABASE_FUNCTION_URL }}/cicd-alert" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -d "{
              \"stage\": \"Test CI/CD Alert\",
              \"status\": \"success\",
              \"details\": \"Triggered by $GITHUB_WORKFLOW on branch $GITHUB_REF, commit $GITHUB_SHA\",
              \"recipient\": \"admin@otiumcreations.com\",
              \"signingSecret\": \"${{ secrets.MAILERLITE_SIGNING_SECRET }}\"
            }"
